---
- name: Deploy web server with PHP to Ubuntu VM
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Install Apache web server and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Enable PHP module in Apache
      apache2_module:
        name: php
        state: present
        force: yes

    - name: Copy HTML file
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Copy PHP file
      copy:
        src: login.php
        dest: /var/www/html/login.php
        mode: '0644'

    - name: Copy welcome.html file
      copy:
        src: welcome.html
        dest: /var/www/html/welcome.html

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
